### ISSUE TITLE
Síntesis de calidad de software.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Ferch0419#1]
[SÍNTESIS Calidad del software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Ferch0419/files/9619647/SINTESIS.Calidad.del.software.pdf)

**Comment by Brisa-4** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
